import './globals.css'
import { Montserrat } from 'next/font/google'
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--font-mont",
})

export const metadata = {
  title: {
    default: 'Thomas',
    template: '%s | Thomas',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
